# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{skittles}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["anthonator"]
  s.date = %q{2011-02-22}
  s.email = %q{anthony@sticksnleaves.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/skittles.rb",
    "lib/skittles/api.rb",
    "lib/skittles/client.rb",
    "lib/skittles/client/checkin.rb",
    "lib/skittles/client/photo.rb",
    "lib/skittles/client/setting.rb",
    "lib/skittles/client/special.rb",
    "lib/skittles/client/tip.rb",
    "lib/skittles/client/user.rb",
    "lib/skittles/client/venue.rb",
    "lib/skittles/configuration.rb",
    "lib/skittles/connection.rb",
    "lib/skittles/request.rb",
    "lib/skittles/version.rb"
  ]
  s.homepage = %q{http://github.com/anthonator/skittles}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Foursquare v2 REST API client library for Ruby}
  s.test_files = [
    "spec/skittles_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth2>, ["~> 0.1.1"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 0.8.1"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_runtime_dependency(%q<oauth2>, ["~> 0.1.1"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 0.8.1"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.4"])
    else
      s.add_dependency(%q<oauth2>, ["~> 0.1.1"])
      s.add_dependency(%q<yajl-ruby>, ["~> 0.8.1"])
      s.add_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_dependency(%q<oauth2>, ["~> 0.1.1"])
      s.add_dependency(%q<yajl-ruby>, ["~> 0.8.1"])
      s.add_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.4"])
    end
  else
    s.add_dependency(%q<oauth2>, ["~> 0.1.1"])
    s.add_dependency(%q<yajl-ruby>, ["~> 0.8.1"])
    s.add_dependency(%q<hashie>, ["~> 1.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.4"])
    s.add_dependency(%q<oauth2>, ["~> 0.1.1"])
    s.add_dependency(%q<yajl-ruby>, ["~> 0.8.1"])
    s.add_dependency(%q<hashie>, ["~> 1.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.4"])
  end
end

